device: cuda:0  # can infer using only 1 gpu
verbose: True  # whether print statistics or not

checkpoints: "logs/lightning_logs/version_15/checkpoints/epoch=12-step=36607.ckpt"  # path to pl checkpoint

image_size: 224  # size of input image

with_labels: True  # Whether your csv file has labels or not
num_workers: 4  # param for infer dataloader
batch_size: 32  # batch size for infer dataloader

# uncomment this, to use online face cropping
# however it is not recommended
# you can only use cpu device as device for face-cropping nn
#face_detector:
#  image_size: 512
#  margin: 100
#  min_face_size: 100
#  thresholds: [0.6, 0.7, 0.7]
#  factor: 0.709
#  device: *device

infer_df: "../../pxl_mlp/projects/liveness-anomaly/datahandlers/test_cropped_data/test_cropped_faces.csv"  # path to csv file with test data
root: "../../pxl_mlp/"  # prefix path to your images
out_folder: "test_logs"
out_file: "test_logs/results.txt"  # path to file you want save your results
